### ISSUE TITLE
allow partial redeem with ERC20Bucket

### ISSUE THREAD

**Issue by gravityblast** [status-im/keycard-redeem#11]

**Comment by bitgamma** [comment]
Why? What is the use case?

**Comment by gravityblast** [comment]
basically spending a part of your gift directly without having to redeem and and spend

**Comment by bitgamma** [comment]
I don't like it because it transforms the redeem bucket in a  almost-a-wallet-but-not-really

**Comment by gravityblast** [comment]
I'm closing it then
