### ISSUE TITLE
update redeem to redeemERC20 and redeemNFT

### ISSUE THREAD

**Issue by gravityblast** [status-im/keycard-redeem#17]
If the 2 contracts implement `erc165`  to expose their `redeemERC20` or `redeemNFT` methods, a dapp can easily understand which token can be redeemed and have a different UI for each one.

**Comment by bitgamma** [comment]
after our discussion yesterday, I think we can add a virtual bucketType function to the base Bucket contract which returns the ERC number in concrete implementations, right?

**Comment by gravityblast** [comment]
@bitgamma yes good idea!

**Comment by gravityblast** [comment]
can we close it in favour of #24 @bitgamma

**Comment by bitgamma** [comment]
yeah, closed
